### PR TITLE
Feature: adds 1804 builds to formula

### PR DESCRIPTION
**Pull request by lsh-0**
The build is failing in 1804 with an `npm bundle` issue. I'm building on 16.04 as I type but I can see new and different errors already

cc @giorgiosironi , @de-code

### CODE REVIEW

**Comment by lsh-0** [comment]
same problem in 16.04:

```
    peerscout--vagrant: ----------
    peerscout--vagrant:           ID: peerscout-client-bundle
    peerscout--vagrant:     Function: cmd.run
    peerscout--vagrant:         Name: npm run bundle
    peerscout--vagrant: 
    peerscout--vagrant:       Result: False
    peerscout--vagrant:      Comment: Command "npm run bundle
    peerscout--vagrant:               " run
    peerscout--vagrant:      Started: 05:19:20.318145
    peerscout--vagrant:     Duration: 657.825 ms
    peerscout--vagrant:      Changes:   
    peerscout--vagrant:               ----------
    peerscout--vagrant:               pid:
    peerscout--vagrant:                   1324
    peerscout--vagrant:               retcode:
    peerscout--vagrant:                   1
    peerscout--vagrant:               stderr:
    peerscout--vagrant:                   /ext/srv/peerscout/client/node_modules/webpack-cli/bin/config-yargs.js:89
    peerscout--vagrant:                   				describe: optionsSchema.definitions.output.properties.path.description,
    peerscout--vagrant:                   				                                          ^
    peerscout--vagrant:                   
    peerscout--vagrant:                   TypeError: Cannot read property 'properties' of undefined
    peerscout--vagrant:                       at module.exports (/ext/srv/peerscout/client/node_modules/webpack-cli/bin/config-yargs.js:89:47)
    peerscout--vagrant:                       at /ext/srv/peerscout/client/node_modules/webpack-cli/bin/webpack.js:60:27
    peerscout--vagrant:                       at Object.<anonymous> (/ext/srv/peerscout/client/node_modules/webpack-cli/bin/webpack.js:515:3)
    peerscout--vagrant:                       at Module._compile (module.js:577:32)
    peerscout--vagrant:                       at Object.Module._extensions..js (module.js:586:10)
    peerscout--vagrant:                       at Module.load (module.js:494:32)
    peerscout--vagrant:                       at tryModuleLoad (module.js:453:12)
    peerscout--vagrant:                       at Function.Module._load (module.js:445:3)
    peerscout--vagrant:                       at Module.require (module.js:504:17)
    peerscout--vagrant:                       at require (internal/module.js:20:19)
    peerscout--vagrant:                   
    peerscout--vagrant:                   npm ERR! Linux 4.4.0-116-generic
    peerscout--vagrant:                   npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "bundle"
    peerscout--vagrant:                   npm ERR! node v6.16.0
    peerscout--vagrant:                   npm ERR! npm  v3.10.10
    peerscout--vagrant:                   npm ERR! code ELIFECYCLE
    peerscout--vagrant:                   npm ERR! peerscout@1.0.0 bundle: `webpack --config webpack.config.js --mode production`
    peerscout--vagrant:                   npm ERR! Exit status 1
    peerscout--vagrant:                   npm ERR! 
    peerscout--vagrant:                   npm ERR! Failed at the peerscout@1.0.0 bundle script 'webpack --config webpack.config.js --mode production'.
    peerscout--vagrant:                   npm ERR! Make sure you have the latest version of node.js and npm installed.
    peerscout--vagrant:                   npm ERR! If you do, this is most likely a problem with the peerscout package,
    peerscout--vagrant:                   npm ERR! not with npm itself.
    peerscout--vagrant:                   npm ERR! Tell the author that this fails on your system:
    peerscout--vagrant:                   npm ERR!     webpack --config webpack.config.js --mode production
    peerscout--vagrant:                   npm ERR! You can get information on how to open an issue for this project with:
    peerscout--vagrant:                   npm ERR!     npm bugs peerscout
    peerscout--vagrant:                   npm ERR! Or if that isn't available, you can get their info via:
    peerscout--vagrant:                   npm ERR!     npm owner ls peerscout
    peerscout--vagrant:                   npm ERR! There is likely additional logging output above.
    peerscout--vagrant:                   
    peerscout--vagrant:                   npm ERR! Please include the following file with any support request:
    peerscout--vagrant:                   npm ERR!     /ext/srv/peerscout/client/npm-debug.log
    peerscout--vagrant:               stdout:
    peerscout--vagrant:                   
    peerscout--vagrant:                   > peerscout@1.0.0 bundle /ext/srv/peerscout/client
    peerscout--vagrant:                   > webpack --config webpack.config.js --mode production
    peerscout--vagrant: ----------
```

**Comment by lsh-0** [comment]
peerscout won't build on 16.04 unless it drops the use of features not available to python 3.5. Removing 16.04 build

**Comment by lsh-0** [comment]
npm bug still needs addressing

**Comment by de-code** [comment]
> peerscout won't build on 16.04 unless it drops the use of features not available to python 3.5. Removing 16.04 build

Yes, it's Python 3.6+. I have no issues with removing 16.04 for PeerScout.

**Comment by de-code** [comment]
> npm bug still needs addressing

The log shows it is trying to use Node 6:
> [2019-03-19T05:41:50.635Z] [54.196.247.180] out:                   npm ERR! node v6.16.0
> [2019-03-19T05:41:50.635Z] [54.196.247.180] out:                   npm ERR! npm  v3.10.10

Whereas the [Dockerfile.client](https://github.com/elifesciences/peerscout/blob/develop/Dockerfile.client#L2) specifies node version `8.12.0`.

Can we upgrade the node version or would it be worth to run the project via Docker instead?

**Comment by lsh-0** [comment]
> The log shows it is trying to use Node 6:

that is what the formula specifies. I'll switch it to nodejs8

> Can we upgrade the node version or would it be worth to run the project via Docker instead?

My first priority is getting everything off of 14.04, we'll leave major changes to deployment like switching to containers for afterwards. I'm not clear on the master plan for them yet.

**Comment by lsh-0** [comment]
nodejs8 added to builder-base, topfile updated

**Comment by lsh-0** [comment]
it looks like peerscout-formula [no longer builds](https://github.com/elifesciences/peerscout-formula/pull/31) without errors anymore. 

if failures in pr-base and pr-head here can be tolerated, this PR is ready to be merged in

update: I've opened a PR here to see if the fix is as simple as bumping nodejs: https://github.com/elifesciences/peerscout-formula/pull/32 it would be good to get this build properly-green

**Review by giorgiosironi — APPROVED** [review]
Also we are creating new servers, so `pr-fresh` is what we care about as `pr-update` wouldn't be necessary for long.

**Comment by de-code** [comment]
The current server seem to be on node 6.16 as well. I replicated the issue using that issue and it went away with version the node 8 version that was specified in Docker file. Doesn't seem to be worth trying to fix it for an old node version.

**Comment by de-code** [comment]
I had another look. Node 6.16 comes with npm 3.10.10, whereas Node 8.12 comes with node 6.4.1.  With Node 6.16, the client is installing webpack-cli 3.3.0, despite the `package-lock.json` file referring to 2.0.9. The more recent version also has `npm ci`, but even that seems to know better. Maybe we should switch to using `yarn` which we use in xPub.

**Comment by lsh-0** [comment]
... it's not clear to me if there are any problems left to be solved here. @de-code , are you ok with Peerscout being upgraded with the changes here? I'll add you as a reviewer

**Review by de-code — APPROVED** [review]

**Comment by lsh-0** [comment]
thanks, @de-code

**Pull request merged**
